disabled_rules:
  - trailing_whitespace
  - function_parameter_count
  - legacy_constructor
  - trailing_comma
  - force_try
  - identifier_name
  - type_name
  - file_length
  - line_length
  - function_body_length
  - type_body_length
  - force_cast
  - xctfail_message
