# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Thanks Diary' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Thanks Diary
	pod 'FSCalendar'
	pod 'AcknowList'
	pod 'lottie-ios'
	pod 'Then'
	pod 'SnapKit', '~> 5.6.0'
end
