# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Thanks Diary' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Thanks Diary
  pod 'FSCalendar'
  pod 'Toast-Swift', '~> 5.0.1'
  pod 'AcknowList'
  pod 'lottie-ios'
end
