# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Thanks Diary' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Thanks Diary
  pod 'FSCalendar'
  pod 'Floaty', '~> 4.2.0'
  pod 'Toast-Swift', '~> 5.0.1'
  pod 'AcknowList'
  pod 'FirebaseAnalytics'
  pod 'FirebaseAuth'
  pod 'FirebaseFirestore'
  pod 'Firebase/RemoteConfig'
  pod 'Firebase/Database'
  pod 'Firebase/Auth'
  pod 'lottie-ios'
  pod 'ObjectMapper', '~> 3.5'
end
